/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static main.OpenFile.openfile;

/**
 *
 * @author Linco
 */
public class Busca extends javax.swing.JFrame {
    public static int encontradas;
    public static Busca pag2;

    /**
     * Creates new form Busca
     */
    public Busca() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Língua:");

        jLabel2.setText("Assunto:");

        jLabel3.setText("Tipo:");

        jLabel4.setText("Dificuldade:");

        jLabel5.setText("Número:");

        jButton1.setText("Ok");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Objetiva");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Discursiva");

        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setText("Fácil");

        buttonGroup3.add(jRadioButton6);
        jRadioButton6.setText("Média");

        jTextField2.setToolTipText("Número de questões");

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setText("Match");

        buttonGroup3.add(jRadioButton8);
        jRadioButton8.setText("Difícil");

        jScrollPane1.setViewportView(jList1);

        jButton3.setText("Limpar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton8))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)
                                        .addGap(45, 45, 45)))))
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton7))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(21, 21, 21))
        );

        jTextField2.getAccessibleContext().setAccessibleName("Número de questões");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**Código do botão Voltar*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pag2.dispose();
        Pg1.pag1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**Código do botão Ok*/
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String Assunto;
        String Lingua;
        if(valida()){
            if(!jList1.isSelectionEmpty()){
                Assunto =  jList1.getSelectedValue();
            }else{
                Assunto = "";
            }
            if(!jList2.isSelectionEmpty()){
                Lingua =  jList2.getSelectedValue();
            }else{
                Lingua = "";
            }
            String Tipo = main.GroupButtonUtils.getSelectedButtonText(buttonGroup2);
            if (Tipo==null){
                Tipo="";
            }
            String Dificuldade = main.GroupButtonUtils.getSelectedButtonText(buttonGroup3);
            if (Dificuldade==null){
                Dificuldade="";
            }
            int numero = Integer.parseInt(jTextField2.getText());
            if(numero>0){
                String Resultado = Banco.Busca.buscar(Assunto, Lingua, Tipo, Dificuldade, numero);
                if(Resultado==null)
                    return;
                if(encontradas!=numero){
                    JOptionPane.showMessageDialog(null, "Foram encontradas apenas "+encontradas+" questões");
                }else{
                    JOptionPane.showMessageDialog(null, "Foram encontradas "+numero+" questões");            
                }
                    int check = Banco.ResultadoBusca.ImprimeResultado(Resultado.split(System.lineSeparator()));
                    String file="Buscas/Busca.txt";
                    Scanner fileIn = new Scanner(file);
                    if (check != 0)
                        return;
                try {
                    openfile(file);
                } catch (IOException ex) {
                    Logger.getLogger(Busca.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Erro nas permissões da pasta do programa!(Erro 10)");
                }
            }
            encontradas = 0;
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**Código do botão Limpar*/
    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        jList2.clearSelection();
        jList1.clearSelection();
        buttonGroup3.clearSelection();
        buttonGroup2.clearSelection();
        jTextField2.setText(null);
    }//GEN-LAST:event_jButton3MouseClicked

    /**verifica se os campos estão preenchidos corretamente */
    private Boolean valida(){
        int i;
        if(!((
            jList2.isSelectionEmpty()&&
            jList1.isSelectionEmpty()&&
            main.GroupButtonUtils.getSelectedButtonText(buttonGroup3)==null&&
            main.GroupButtonUtils.getSelectedButtonText(buttonGroup2)==null))){
            try{
                i = Integer.parseInt(jTextField2.getText());
            }catch(NumberFormatException exception){
                JOptionPane.showMessageDialog(null, "Por favor digite um número inteiro");
                jTextField2.setText(null);
                return false;
            }
            return true;
        }else{
            JOptionPane.showMessageDialog(null, "Por favor selecione ao menos um dos filtros");
        }
        return false;
    }
    
    /**
     * Funçao que inicializa a lista de assuntos ja existentes
     */
    public void setassunto(){
        DefaultListModel list = new DefaultListModel();
        try{
            File arq = new File("Indices/Assuntos.txt");
            if (!arq.exists()){
                JOptionPane.showMessageDialog(null, "Nenhum arquivo no banco de dados ou erro desconhecido com as permissões da pasta do programa!(Erro 11)");
                return;
            }
            Scanner fileIn;
            fileIn = new Scanner(arq);
            while (fileIn.hasNextLine()){
                list.addElement(fileIn.nextLine());
            }
            fileIn.close();
            jList1.setModel(list);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Busca.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Funçao que inicializa a lista de linguas ja existentes
     */
    public void setlingua(){
        DefaultListModel list = new DefaultListModel();
        try{
            File arq = new File("Indices/Línguas.txt");
            if (!arq.exists()){
                JOptionPane.showMessageDialog(null, "Nenhum arquivo no banco de dados ou erro desconhecido com as permissões da pasta do programa!(Erro 11)");
                return;
            }
            Scanner fileIn;
            fileIn = new Scanner(arq);
            while (fileIn.hasNextLine()){
                list.addElement(fileIn.nextLine());
            }
            fileIn.close();
            jList2.setModel(list);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Busca.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Nenhum arquivo no banco de dados ou erro desconhecido com as permissões da pasta do programa!(Erro 38)");
            pag2.dispose();
            Pg1.pag1.setVisible(true);
        }
    }
    
    /**verifica o que não existe no banco e remove da interface*/
    public void verificabanco(){
        setassunto();
        setlingua();
        File arq = new File("Indices/Objetiva.txt");
        if(!arq.exists())
            jRadioButton3.setVisible(false);
        arq = new File("Indices/Discursiva.txt");
        if(!arq.exists())
            jRadioButton4.setVisible(false);
        arq = new File("Indices/Match.txt");
        if(!arq.exists())
            jRadioButton7.setVisible(false);
        arq = new File("Indices/Fácil.txt");
        if(!arq.exists())
            jRadioButton5.setVisible(false);
        arq = new File("Indices/Média.txt");
        if(!arq.exists())
            jRadioButton6.setVisible(false);
        arq = new File("Indices/Difícil.txt");
        if(!arq.exists())
            jRadioButton8.setVisible(false);
        
    }
    
    /**inicia e abre a tela de busca*/
    public static void run() {
        int numero, i=0;
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro nas permissões da pasta do programa!(Erro 12)");
        }
        //</editor-fold>
        
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Busca busca = new Busca();
                busca.verificabanco();
                pag2 = busca;
                pag2.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
