/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Linco
 */
public class Pg1 extends javax.swing.JFrame {

    /**
     * Página principal do programa
     */
    public Pg1() {
        initComponents();
    }
    
    /**Flags para controle das interaçoes entre funções*/
    Boolean Edit = false, assuntosetted=false, linguasetted=false;
    String nome;
    public static Pg1 pag1;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        fileChooser = new javax.swing.JFileChooser();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jPopupMenu1.setAlignmentX(0.5F);
        jPopupMenu1.setAlignmentY(0.0F);
        jPopupMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPopupMenu1MouseClicked(evt);
            }
        });

        jPopupMenu2.setAlignmentX(0.5F);
        jPopupMenu2.setAlignmentY(0.0F);
        jPopupMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPopupMenu2MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setToolTipText("Assunto");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("Questão");
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.getAccessibleContext().setAccessibleName("Questão");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Fácil");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Média");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Difícil");

        jLabel1.setText("Dificuldade:");

        jLabel2.setText("Língua:");

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("Objetiva");

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setText("Discursiva");

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setText("Match");

        jLabel3.setText("Tipo:");

        jButton3.setText("Busca");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Assunto:");

        jLabel5.setText("Questão:");

        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });

        jMenu1.setText("Arquivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setText("Novo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ferramentas");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Reparar o Banco de Questões");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton6)
                                    .addComponent(jRadioButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton7))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(jButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(0, 336, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton6)
                                .addComponent(jRadioButton7)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextField1.getAccessibleContext().setAccessibleName("Assunto");
        jTextField2.getAccessibleContext().setAccessibleName("Língua");
        jTextField2.getAccessibleContext().setAccessibleDescription("Língua");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Funçao que inicializa a popup de assuntos ja existentes
     */
    public void setassunto(){
        String Assunto;
       ActionListener menuListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent event) {
                jTextField1.setText(event.getActionCommand());
              }
        };
        try{
            File arq = new File("Indices/Assuntos.txt");
            Scanner fileIn;
            fileIn = new Scanner(arq);
            while (fileIn.hasNextLine()){
                Assunto=fileIn.nextLine();
                JMenuItem item = new JMenuItem(Assunto);
                item.addActionListener(menuListener);
                jPopupMenu1.add(item);
            }
            fileIn.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Busca.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro nas permissões da pasta do programa!(Erro 31)");
        }
    }
    
    /**
     * Funçao que inicializa a popup de Linguas ja existentes
     */
    public void setlingua(){
        String Lingua;
        ActionListener menuListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent event) {
                jTextField2.setText(event.getActionCommand());
              }
        };
        try{
            File arq = new File("Indices/Línguas.txt");
            Scanner fileIn;
            fileIn = new Scanner(arq);
            while (fileIn.hasNextLine()){
                Lingua=fileIn.nextLine();
                JMenuItem item = new JMenuItem(Lingua);
                item.addActionListener(menuListener);
                jPopupMenu2.add(item);
            }
            fileIn.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Busca.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro nas permissões da pasta do programa!(Erro 35)");
        }
    }
    
    /**Código do botão de Salvar/Editar*/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(valida()){
            String Assunto =  jTextField1.getText();
            String Lingua =  jTextField2.getText();
            String Tipo = main.GroupButtonUtils.getSelectedButtonText(buttonGroup2);
            String Dificuldade = main.GroupButtonUtils.getSelectedButtonText(buttonGroup1);
            String Questao =  jTextArea1.getText();
            if(Edit == true){
                try {
                    int edited = main.Editar.edit(Assunto, Lingua, Tipo, Dificuldade, Questao, nome);
                    jTextField1.setText(null);
                    jTextArea1.setText(null);
                    jTextField2.setText(null);
                    buttonGroup2.clearSelection();
                    buttonGroup1.clearSelection();
                    Edit = false;
                    jButton1.setText("Salvar");
                    jButton2.setText("Limpar");
                } catch (IOException ex) {
                    Logger.getLogger(Pg1.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Erro nas permissões da pasta do programa!(Erro 7)");
                }
            }else{
                try {
                    int saved = main.Save.salvar(Assunto, Lingua, Tipo, Dificuldade, Questao);
                } catch (IOException ex) {
                    Logger.getLogger(Pg1.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Erro nas permissões da pasta do programa!(Erro 8)");
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**Código do botão Limpar*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText(null);
        jTextArea1.setText(null);
        jTextField2.setText(null);
        buttonGroup2.clearSelection();
        buttonGroup1.clearSelection();
        Edit = false;
        jButton1.setText("Salvar");
        jButton2.setText("Limpar");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**Código do menu Novo*/
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jButton2ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**Código do menu Abrir*/
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        File dir = new File ("Questoes/");
        fileChooser.setCurrentDirectory(dir);
        int returnVal = fileChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
           try {
               jButton2ActionPerformed(evt);
               File file = fileChooser.getSelectedFile();
               nome = file.getName();
               try (Scanner fileIn = new Scanner(file)) {
                   String lingua = fileIn.nextLine();
                   jTextField2.setText(lingua);
                   String Assunto = fileIn.nextLine();
                   jTextField1.setText(Assunto);
                   String Tipo = fileIn.nextLine();
                   if(Tipo.equals("Objetiva")){
                       buttonGroup2.setSelected(jRadioButton6.getModel(), rootPaneCheckingEnabled);
                   }
                   if(Tipo.equals("Discursiva")){
                       buttonGroup2.setSelected(jRadioButton7.getModel(), rootPaneCheckingEnabled);
                   }
                   if(Tipo.equals("Match")){
                       buttonGroup2.setSelected(jRadioButton8.getModel(), rootPaneCheckingEnabled);
                   }
                   String Dificuldade = fileIn.nextLine();
                   if(Dificuldade.equals("Fácil")){
                       buttonGroup1.setSelected(jRadioButton1.getModel(), rootPaneCheckingEnabled);
                   }
                   if(Dificuldade.equals("Média")){
                       buttonGroup1.setSelected(jRadioButton2.getModel(), rootPaneCheckingEnabled);
                   }
                   if(Dificuldade.equals("Difícil")){
                       buttonGroup1.setSelected(jRadioButton3.getModel(), rootPaneCheckingEnabled);
                   }
                   fileIn.nextLine();
                   while(fileIn.hasNextLine()){
                       String Texto = fileIn.nextLine();
                       jTextArea1.append(Texto+System.lineSeparator());
                   }
               }
               Edit = true;
               jButton1.setText("Editar");
               jButton2.setText("Cancelar");
           } catch (FileNotFoundException ex) {
               Logger.getLogger(Pg1.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(null, "Erro nas permissões da pasta do programa!(Erro 9)");
           }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**Código do botão Busca*/
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        GUI.Busca.run();
        pag1.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**Mostra/Esconde a popup de assuntos existentes */
    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        if(!assuntosetted){
            jPopupMenu1.removeAll();
            File file = new File("Indices/Assuntos.txt");
            if(file.exists())
                setassunto();
            jPopupMenu1.show(this, evt.getX()+100, evt.getY()+90);
            assuntosetted=true;
        }else{
            assuntosetted=false;
            jPopupMenu1.setVisible(false);
        }
    }//GEN-LAST:event_jTextField1MouseClicked

    /**Esconde a popup de assuntos existentes após eventual escolha dentre eles  */
    private void jPopupMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPopupMenu1MouseClicked
        jPopupMenu1.setVisible(false);
    }//GEN-LAST:event_jPopupMenu1MouseClicked

    /** Código do botão Reparar Banco.Deleta e recria os arquivos de indice*/
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       int i=1;
        String Assunto, Lingua, Tipo, Dificuldade, Questao;
        try{
            DeletaPastas(new File("Indices"));
            File file = new File("Indices/Assunto");
            Scanner fileIn;
            PrintWriter writer;
            if(!file.exists())
                file.mkdirs();
            file = new File("Indices/Língua/");
            if(!file.exists())
                file.mkdir();
            file = new File("Questoes/"+i+".txt");
            while(file.exists()){
                fileIn = new Scanner(file);
                Lingua=fileIn.nextLine();
                Assunto=fileIn.nextLine();
                Tipo=fileIn.nextLine();
                Dificuldade=fileIn.nextLine();
                fileIn.nextLine();
                Questao=fileIn.nextLine();
                file = new File("Indices/IndiceDeNomes.txt");
                if(!file.exists()) {
                    file.createNewFile();
                }
                writer = new PrintWriter(new FileWriter("Indices/IndiceDeNomes.txt", true));
                writer.println(i+".txt");
                writer.close();
                fileIn.close();
                Banco.Lingua.adicionar(Lingua, i+".txt");
                Banco.Assunto.adicionar(Assunto, i+".txt");
                Banco.Tipo.adicionar(Tipo, i+".txt");
                Banco.Dificuldade.adicionar(Dificuldade, i+".txt");
                i++;
                file = new File("Questoes/"+i+".txt");
            }
            JOptionPane.showMessageDialog(null, "Banco de dados recuperado com sucesso!");
        } catch (IOException ex) {
            Logger.getLogger(Pg1.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro nas permissões da pasta do programa! (Erro 34)");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**Mostra/Esconde a popup de linguas existentes */
    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        if(!linguasetted){
            jPopupMenu2.removeAll();
            File file = new File("Indices/Línguas.txt");
            if(file.exists())
                setlingua();
            jPopupMenu2.show(this, evt.getX()+100, evt.getY()+55);
            linguasetted=true;
        }else{
            linguasetted=false;
            jPopupMenu2.setVisible(false);
        }
    }//GEN-LAST:event_jTextField2MouseClicked

    /**Esconde a popup de linguas existentes após eventual escolha dentre elas  */
    private void jPopupMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPopupMenu2MouseClicked
        jPopupMenu2.setVisible(false);
    }//GEN-LAST:event_jPopupMenu2MouseClicked
    
    /**Deleta pastas, usada para remover as pastas de indices ao refazer o banco
     * @param dir
     * @return  */
    public static boolean DeletaPastas(File dir){
           if (dir.isDirectory()) {  
               String[] children = dir.list();  
               for (String children1 : children) {
                   boolean success = DeletaPastas(new File(dir, children1));
                   if (!success) {
                       return false;
                   }
               }  
           }  
         
           // Agora o diretório está vazio, restando apenas deletá-lo.  
           return dir.delete();  
       }  
     
    /**verifica se todos campos estão preenchidos corretamente */
    private Boolean valida(){
        String Assunto =  jTextField1.getText();
        String Lingua =  jTextField2.getText();
        if((!Lingua.contains("\\"))&&
            (!Lingua.contains("/"))&&
            (!Lingua.contains("\""))&&
            (!Lingua.contains("*"))&&
            (!Lingua.contains("?"))&&
            (!Lingua.contains(":"))&&
            (!Lingua.contains("<"))&&
            (!Lingua.contains(">"))&&
            (!Lingua.contains("|"))){
            if((!Assunto.contains("\\"))&&
            (!Assunto.contains("/"))&&
            (!Assunto.contains("\""))&&
            (!Assunto.contains("*"))&&
            (!Assunto.contains("?"))&&
            (!Assunto.contains(":"))&&
            (!Assunto.contains("<"))&&
            (!Assunto.contains(">"))&&
            (!Assunto.contains("|"))){
                if(!(jTextField1.getText().isEmpty()||
                    jTextArea1.getText().isEmpty()||
                    jTextField2.getText().isEmpty()||
                    main.GroupButtonUtils.getSelectedButtonText(buttonGroup2)==null||
                    main.GroupButtonUtils.getSelectedButtonText(buttonGroup1)==null)){
                        return true;
                }else{
                    JOptionPane.showMessageDialog(null, "Por favor complete todos os campos");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Por favor não utilize \\, /, |, \", :, *, ?, < ou > no campo Assunto");
                jTextField1.setText(null);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por favor não utilize \\, /, |, \", :, *, ?, < ou > no campo Língua");
                
            jTextField2.setText(null);
        }
        return false;
    }
    
    /**inicia e mostra a pagina principal*/
    public static void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro nas permissões da pasta do programa!(Erro 6)");
        }
        //</editor-fold>
        
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                pag1=new Pg1();
                pag1.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
